In [82]:
from queue import PriorityQueue, SimpleQueue, LifoQueue
from random import random
from functools import reduce
from collections import namedtuple
from pprint import pprint
import numpy as np

Sets the initial constant for the problem

In [83]:
PROBLEM_SIZE = 5
NUM_SETS = 10

Create randomly the NUM_SETS array of lenght PROBLEM_SIZE, with a probability of 30% to have a true value in the singles line.
And I choose how **state** this rappresentation **({sets_taken},{sets_not_taked})** with **sets_taken** and **sets_not_taked** the index of the sets

In [84]:
SETS = tuple(
    np.array([random() < 0.3 for _ in range(PROBLEM_SIZE)])
    for _ in range(NUM_SETS)
)
State = namedtuple("State", ["taken", "not_taken"])

To evaluate the goal:
1. take all the sets selected in the current state
2. apply a or between all this sets with the reduce function
3. return true just if we have all true in the resulted array

Note: we can have overlapping, it is not a limitation in the problem, so the or is a good choice

In [85]:
def goal_check(state):
    return np.all(
        reduce(
            np.logical_or,
            [SETS[i] for i in state.taken],
            False,
        )
    )

Now I check if the problem is solvable, because if I cannot solve it with all the sets the problem is not solvable

In [86]:
assert goal_check(State(set(range(NUM_SETS)), set())), "Problem not solvable"

Define a function search that with a frontier apply the path search and return the goal state

In [87]:
def search(frontier):
    current_state = frontier.get()

    # to count the number of sets put in the frontier
    counter = 0
    while not goal_check(current_state):
        counter += 1
        for action in current_state.not_taken:
            new_state = State(
                current_state.taken ^ {action},
                current_state.not_taken ^ {action},
            )
            frontier.put(new_state)
        current_state = frontier.get()

    print(f"Solved in {counter} steps")
    return current_state

With a PriorityQueue I don't know the priority that the frontier apply, so we don't know the real type of algorithm. But with a **SimpleQueue** we are solving the problem with a **Breadth First**, in this way we are solving the problem with the optimal solution in the sense of **minimum number of tiles to covering all the line**.
With a **LifoQueue** I'm searching the solution with the **Depth First** that don't find the optimal solution but it is more quick.

In [88]:
# define a SimpleQueue, and LifoQueue how frontiers
fifo = SimpleQueue()
lifo = LifoQueue()
# put the initial state (taken is empty and not taked is all the sets) in the frontiers
fifo.put(State(set(), set(range(NUM_SETS))))
lifo.put(State(set(), set(range(NUM_SETS))))

breadth_solution_state = search(fifo)
depth_solution_state = search(lifo)

Solved in 28 steps
Solved in 3 steps


In [89]:
print(
    f"Solution with a Breadth Search:\n{breadth_solution_state}\nSolution with a Depth Search:\n{depth_solution_state}"
)

Solution with a Breadth Search:
State(taken={9, 1}, not_taken={0, 2, 3, 4, 5, 6, 7, 8})
Solution with a Depth Search:
State(taken={8, 9, 7}, not_taken={0, 1, 2, 3, 4, 5, 6})


In this case we don't have any type of cost (we are assuming the number of sets), if we define a different cost, for example a solution with the smallest number of overlap. In the sense that the **cost is the total number of true in taken sets**. To solve the problem , in this case we have to add the cost how key and use a PriorityQueue to order the queue to solve a **Dijkstra**. In this way we are searching for a solution with the **minimum number of overlapping**.

In [90]:
def cost_function(taken):
    return sum([np.sum(SETS[i]) for i in taken])

In [91]:
def search_dijkstra(frontier):
    current_state = frontier.get()

    # to count the number of sets put in the frontier
    counter = 0
    while not goal_check(current_state):
        counter += 1
        for action in current_state.not_taken:
            new_state = State(
                current_state.taken ^ {action},
                current_state.not_taken ^ {action},
            )
            frontier.put((cost_function(new_state.taken), new_state))
        current_state = frontier.get()[1]

    print(f"Solved in {counter} steps")
    return current_state

In [92]:
# define a PriorityQueue how frontiers
frontier = PriorityQueue()

# put the initial state (taken is empty and not taked is all the sets) in the frontiers
frontier.put(State(set(), set(range(NUM_SETS))))

dijkstra_solution_state = search_dijkstra(frontier)

Solved in 177 steps


In [93]:
dijkstra_solution_state

State(taken={1, 2, 3}, not_taken={0, 4, 5, 6, 7, 8, 9})

In [94]:
pprint([SETS[i] for i in dijkstra_solution_state.taken])

[array([False, False,  True,  True, False]),
 array([False,  True, False, False, False]),
 array([ True, False, False, False,  True])]


Now I want to implemente a version of **Informed search**, so with a **Euristich** that estimate the distances from a state to the goal, and use it to modify the search.<br>
I define **h(n)** heuristic of node n with the **number of false that I have considering the OR of all the taken sets**, i.e. number of true that are missing for the goal.

**Greedy Best First** using just the euristich **h(n)**. <br>


In [95]:
def heuristic(taken):
    return PROBLEM_SIZE - sum(reduce(np.logical_or, [SETS[i] for i in taken]))

In [96]:
def greedy_best_search(frontier):
    current_state = frontier.get()

    steps = 0
    while not goal_check(current_state):
        steps += 1
        for action in current_state.not_taken:
            new_state = State(
                current_state.taken ^ {action},
                current_state.not_taken ^ {action},
            )
            frontier.put((heuristic(new_state.taken), new_state))
        _, current_state = frontier.get()
    print(f"Solved in {steps} steps and with {len(current_state.taken)} tiles")
    return current_state

In [97]:
# define a PriorityQueue how frontiers
frontier = PriorityQueue()

# put the initial state (taken is empty and not taked is all the sets) in the frontiers
frontier.put(State(set(), set(range(NUM_SETS))))

greedy_solution = greedy_best_search(frontier)
pprint([SETS[i] for i in greedy_solution.taken])

Solved in 3 steps and with 3 tiles
[array([ True, False,  True, False,  True]),
 array([False, False,  True,  True, False]),
 array([False,  True, False, False, False])]


## Lab1 with A* - 19/10/2023
**A\* Search** where the evalutation function **f(n) = g(n) + h(n)**:<br>
-**g(n)** the cost from start to node n, so the **number of tiles in the taken set**.<br>
-**h(n)** the same heuristic function used in the greedy best first.

In [98]:
def A_star(frontier):
    current_state = frontier.get()

    # to count the number of sets put in the frontier
    counter = 0
    while not goal_check(current_state):
        counter += 1
        for action in current_state.not_taken:
            new_state = State(
                current_state.taken ^ {action},
                current_state.not_taken ^ {action},
            )
            frontier.put(
                (
                    len(new_state.taken) + heuristic(new_state.taken),
                    new_state,
                )
            )
        current_state = frontier.get()[1]

    print(f"Solved in {counter} steps")
    return current_state

In [99]:
# define a PriorityQueue how frontiers
frontier = PriorityQueue()

# put the initial state (taken is empty and not taked is all the sets) in the frontiers
frontier.put(State(set(), set(range(NUM_SETS))))

A_star_solution = A_star(frontier)

Solved in 3 steps


In [100]:
pprint([SETS[i] for i in A_star_solution.taken])

[array([False, False,  True,  True, False]),
 array([ True,  True, False, False,  True])]


How visible **A\*** get the **optimal solution** (2 tiles) with **3 steps**, so better than **Breadth First** that find the optimal solution with **28 steps**.